### ISSUE TITLE
Feature Request: Show progress of review on /reviews page

### ISSUE THREAD

**Issue by arosales** [juju-solutions/review-queue#27]
When looking at the reviews on https://review.jujucharms.com/reviews, I would like to see, in this display, the review **complete percentage**. Perhaps this is calculated by counting number of passes/total-passes-need.

**Comment by arosales** [comment]
Also in this view I think it would be useful to show the number of **fails**. As a user I would like to see quickly see for my submissions what is the current review progress, and if there any fails.  Specifically, if there are any fails I need to open up the review and take action.  

As a reviewee I want to know where I am currently at in the review, and if any action is needed by me. In addition to the Status field, or supplement the status field

As a reviewer I want to see the progress of reviews.

-thanks,
Antonio

**Comment by tvansteenburgh** [comment]
Coming soon...

<img width="1213" alt="progress-bars" src="https://cloud.githubusercontent.com/assets/801183/17824879/8ae7a8be-6632-11e6-8cd3-5717eac2b5a1.png">
