### ISSUE TITLE
Feature Request: Add Complete and Closed Status

### ISSUE THREAD

**Issue by arosales** [juju-solutions/review-queue#29]
When all "Must" policy points have been fulfilled and progress is therefore 100% (see #27) we should show a status of "Complete" so a charmer can filter on this (see #28) and take promulgation action. I am guessing at post a promulgation a ~charmer should be able to mark the review as Closed.

As a reviewer I am not sure how a review get put into a state to signal a ~charmer needs to promulgate, or how to close out a review post promulgation.

**Comment by tvansteenburgh** [comment]
I think this was addressed on our call, but if not, feel free to reopen. To summarize:

Once the review gets the required number of up-votes, it automatically goes to Approved status, indicating that it's ready for promulgation. Once a charmer does the promulgation, he/she simply clicks the Close button and the review is closed (goes to Closed status and disappears from the default list view).
